Repository Team-Ampersand/Dotori-V3-Member, pull requests merged in 2024-04, with the labels that each got.

#12 #10 멤버 아이디 리스트에 포함된 멤버 반환
  build.gradle.kts
  src/main/kotlin/ampersand/userservice/application/MemberService.kt
  src/main/kotlin/ampersand/userservice/application/MemberServiceImpl.kt
  src/main/kotlin/ampersand/userservice/application/dto/MemberIds.kt
  src/main/kotlin/ampersand/userservice/persistence/port/MemberRepositoryPort.kt
  src/main/kotlin/ampersand/userservice/persistence/repository/MemberRepositoryImpl.kt
  src/main/kotlin/ampersand/userservice/presentation/MemberHandler.kt
  src/main/kotlin/ampersand/userservice/presentation/MemberRouter.kt
Labels: 2️⃣ Priortiy: Medium, 📬 Type: API

#14 Member 상태 업데이트 Saga
  build.gradle.kts
  src/main/kotlin/ampersand/userservice/application/MemberConsumer.kt
  src/main/kotlin/ampersand/userservice/application/MemberServiceImpl.kt
  src/main/kotlin/ampersand/userservice/infrastructure/saga/MemberStatusCommandSaga.kt
  src/main/kotlin/ampersand/userservice/infrastructure/saga/MemberStatusCommandSagaImpl.kt
  src/main/kotlin/ampersand/userservice/persistence/MassageStatus.kt
  src/main/kotlin/ampersand/userservice/persistence/MemberEntity.kt
  src/main/kotlin/ampersand/userservice/persistence/SelfStudyStatus.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#16 #15 security config logic
  src/main/kotlin/ampersand/userservice/infrastructure/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High

#20 #19 endpoint 변경
  src/main/kotlin/ampersand/userservice/presentation/MemberRouter.kt
Labels: 2️⃣ Priortiy: Medium

#21 chore :: sync query 메서드 작성, sage step 적용<< suspend 제거
  src/main/kotlin/ampersand/userservice/application/MemberConsumer.kt
  src/main/kotlin/ampersand/userservice/infrastructure/saga/MemberStatusCommandSaga.kt
  src/main/kotlin/ampersand/userservice/infrastructure/saga/MemberStatusCommandSagaImpl.kt
  src/main/kotlin/ampersand/userservice/persistence/port/MemberRepositoryPort.kt
  src/main/kotlin/ampersand/userservice/persistence/repository/CustomMemberRepositoryImpl.kt
Labels: 0️⃣ Priority: Critical, 1️⃣ Priority: High
